version: "3.7"

services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000" # 開発用
      - "4000:4000" # 本番用
    working_dir: /app
    volumes:
      - ./app/src/calapp:/app
    # env_file:
    #   - ./app/.env
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "yarn start"

  api:
    build:
      context: .
      dockerfile: ./api/build/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    tty: true

  db:
    image: postgres:14
    container_name: db
    ports:
      - "5434:5434"
    volumes:
      - ./db/postgres/init.d:/docker-entrypoint-initdb.d
      - ./db/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root       # DB USER
      POSTGRES_PASSWORD: root   # DB Password
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:6.13
    container_name: pgadmin4
    ports:
      - "8000:80"
    volumes:
      - ./db/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com   # pgAdmin Address
      PGADMIN_DEFAULT_PASSWORD: SuperSecret  # pgAdmin Password
    links:
      - db
    restart: always